### ISSUE TITLE
Loading bays

### ISSUE THREAD

**Issue by davidpnewton** [zlant/parking-lanes#118]
The tag parking:condition:*=loading shows up as an unsupported configuration and yet on the OSM wiki page documentation shows it should be used for explicitly-signed loading bays. Such explicitly-signed loading bays are fairly common in the UK.

Please add parking:condition:*=loading as a supported configuration for the viewer and editor.

**Comment by riiga** [comment]
Since `loading_only` is now an officially supported restriction in the new tagging schema, I second that it would be great if support for it was added.

Here are some examples of currently unsupported cases:

[No parking base restriction with loading only part of the day](https://zlant.github.io/parking-lanes/#20/58.40879/15.62587) ([OSM way](https://www.openstreetmap.org/way/1123459233))
```
parking:right:restriction = no_parking
parking:right:restriction:conditional = loading_only @ (Mo-Fr 08:00-11:00)
parking:right:restriction:reason = loading_zone
```

[Loading only base restriction](https://zlant.github.io/parking-lanes/#20/58.41116/15.62627) ([OSM way](https://www.openstreetmap.org/way/746403760))
```
parking:right:restriction = loading_only
parking:right:restriction:reason = loading_zone
```

My knowledge of TypeScript (or web development in general) is unfortunately limited, otherwise I would try a pull request.

**Comment by riiga** [comment]
Nice work! I think this issue can be closed.
