### ISSUE TITLE
Residential parking renders as no-stopping red

### ISSUE THREAD

**Issue by kaneap** [zlant/parking-lanes#145]
Tagging a road for residential permit parking according to [the wiki](https://wiki.openstreetmap.org/wiki/Street_parking#Residential_parking_permits,_parking_zones) causes the street to be rendered with "no stopping" red.

For example:
- `parking:right = lane`
- `parking:right:access = private`
- `parking:right:orientation = parallel`
- `parking:right:zone = W`
renders like this:
![image](https://user-images.githubusercontent.com/35740782/225780756-92e18426-6c46-4b9d-ad87-3cb3ee4bda47.png)
(this example is located at https://zlant.github.io/parking-lanes/#20/50.72934/7.09741)

**Comment by tordans** [comment]
@kaneap please add a link to the location, so its easier to review in the editor. 
What rendering would you expect?

**Comment by kaneap** [comment]
@tordans the Pink "Residents only" color as displayed in the legend

**Comment by kayD** [comment]
The color scheme is problematic imho. While I am not color blind, I find it next to impossible to discern the reddish colors.
https://zlant.github.io/parking-lanes/#19/49.78873/9.93285
![image](https://github.com/zlant/parking-lanes/assets/316554/4fc87699-b277-46cf-9c50-d32d62a78fc8)
Even with unfolded legend:
![image](https://github.com/zlant/parking-lanes/assets/316554/21c6346f-12b3-4d45-88cd-58a458ccc1b0)
The Peterplatz left side seems to be pinkish (residents), while in the Bergmeistergasse it looks between no-stopping, not applicable and residents.

Also here 
![image](https://github.com/zlant/parking-lanes/assets/316554/9e0d7151-6b72-4501-a60e-3bb78d6fa031)
the parking lot area has a hue I cannot find in the legend. The next similar would be no stopping.
This is due to the transparency of the rendering.

**Suggestion**:
The colors should be well separated, without being a random swatch of colors.
Green should be "free"/no payment, blue for payment, and red-yellow for "not allowed" in general.

"Fire red" for absolutely no standing like a fire lane, red for no stopping, yellow for loading only.

So, "for customers" will be likely not somewhere that you could choose for a trip into the city, so should be somewhere between green and red.
Free parking should clearly be the brightest green (the one that is currently used for customers). All restrictions (time limit, customers only) should tend to a darker, or more blueish, or reddish color.

The "not applicable" is unclear (possibly a tagging error) - it should have the most "smells funny" color: pink. (Maybe dotted or so to indicate problem)

**Comment by kaneap** [comment]
@kayD I believe the issues you raise are a different issue. I'd recommend opening a different issue to discuss the coloring strategy.

**Comment by kaneap** [comment]
On the other hand, the way directly opposite (https://www.openstreetmap.org/way/38450772) always renders pink, while in theory it should only render pink from 16:00-09:00. Its parking tags are:
`parking:right=lane`
`parking:right:access:conditional=private @ 16:00-09:00`
`parking:right:fee=no`
`parking:right:motorcar=designated`
`parking:right:orientation=parallel`
`parking:right:zone=A`
I believe this should render as free parking green from 09:00-16:00 and residents pink from 16:00-09:00.

**Comment by kaneap** [comment]
Appears to be fixed now, I'll close my issue now.
